import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provide";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "SimpLHealth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
